### ISSUE TITLE
wrong mana farm

### ISSUE THREAD

**Issue by flezi** [Praoubl/technetium#2]
By using another kind of tnt you can bypass the duping protection.
[world](https://mega.nz/file/wkAiXDza#_qiqJc8xzibZnEUqozp9T8Z3rDNJgSn0wh4NyBI3klg)
![ynCmwEd](https://github.com/user-attachments/assets/8dabad90-ec4b-4993-958c-1f7799906e59)

**Comment by Praoubl** [comment]
Interesting, probably best reported to botania's repo.
